---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchmen
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchmen-clusterrolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watchmen-clusterrole
subjects:
  - kind: ServiceAccount
    name: watchmen
    namespace: kube-system